// Catálogo municipal de Nicaragua, disponible sin conexión.
// Códigos: https://www.inide.gob.ni/docu/censos2005/CifrasMun/tablas_cifras.htm
// Nombres y cabeceras: Ley 59 consolidada, La Gaceta 189 (13/10/2021),
// páginas 10022–10027. Consultado el 07/10/2026.
// https://cam.gob.ni/wp-content/uploads/2025/04/1.-LEY-1048-LEY-DEL-DIGESTO-JURIDICO-NICARAGUENSE-DE-LA-MATERIA-MUNICIPAL.pdf
class NicaraguaOriginPlace {
  const NicaraguaOriginPlace(
    this.municipalityCode,
    this.department,
    this.municipality, {
    String? city,
    this.aliases = const [],
  }) : city = city ?? municipality;

  final String municipalityCode;
  final String department;
  final String municipality;
  final String city;
  final List<String> aliases;

  String get searchText =>
      '$city $municipality $department ${aliases.join(' ')}';
}

NicaraguaOriginPlace? findNicaraguaOriginPlace(
  String city,
  String municipality,
) {
  for (final place in nicaraguaOriginPlaces) {
    if (place.city == city.trim() &&
        place.municipality == municipality.trim()) {
      return place;
    }
  }
  return null;
}

const nicaraguaOriginPlaces = <NicaraguaOriginPlace>[
  NicaraguaOriginPlace('3505', 'León', 'Achuapa'),
  NicaraguaOriginPlace('6535', 'Chontales', 'Acoyapa'),
  NicaraguaOriginPlace('8030', 'Rivas', 'Altagracia'),
  NicaraguaOriginPlace('8010', 'Rivas', 'Belén'),
  NicaraguaOriginPlace(
    '9110',
    'Región Autónoma de la Costa Caribe Norte',
    'Puerto Cabezas',
    city: 'Bilwi',
    aliases: ['Bilwi (Puerto Cabezas)'],
  ),
  NicaraguaOriginPlace(
    '9340',
    'Región Autónoma de la Costa Caribe Sur',
    'Bluefields',
  ),
  NicaraguaOriginPlace('5010', 'Boaco', 'Boaco'),
  NicaraguaOriginPlace(
    '9305',
    'Región Autónoma de la Costa Caribe Sur',
    'Paiwas',
    city: 'Bocana de Paiwas',
  ),
  NicaraguaOriginPlace(
    '9120',
    'Región Autónoma de la Costa Caribe Norte',
    'Bonanza',
  ),
  NicaraguaOriginPlace('8020', 'Rivas', 'Buenos Aires'),
  NicaraguaOriginPlace('5015', 'Boaco', 'Camoapa'),
  NicaraguaOriginPlace('6035', 'Masaya', 'Catarina'),
  NicaraguaOriginPlace('3060', 'Chinandega', 'Chichigalpa'),
  NicaraguaOriginPlace('3045', 'Chinandega', 'Chinandega'),
  NicaraguaOriginPlace('3015', 'Chinandega', 'Cinco Pinos'),
  NicaraguaOriginPlace('0550', 'Nueva Segovia', 'Ciudad Antigua'),
  NicaraguaOriginPlace('4065', 'Matagalpa', 'Ciudad Darío'),
  NicaraguaOriginPlace('5522', 'Managua', 'Ciudad Sandino'),
  NicaraguaOriginPlace('6505', 'Chontales', 'Comalapa'),
  NicaraguaOriginPlace('2510', 'Estelí', 'Condega'),
  NicaraguaOriginPlace('3055', 'Chinandega', 'Corinto'),
  NicaraguaOriginPlace(
    '9335',
    'Región Autónoma de la Costa Caribe Sur',
    'Corn Island',
  ),
  NicaraguaOriginPlace(
    '6507',
    'Chontales',
    'San Francisco de Cuapa',
    city: 'Cuapa',
    aliases: ['San Francisco Cuapa', 'Cuapa'],
  ),
  NicaraguaOriginPlace('8050', 'Rivas', 'Cárdenas'),
  NicaraguaOriginPlace('0530', 'Nueva Segovia', 'Dipilto'),
  NicaraguaOriginPlace('7520', 'Carazo', 'Diriamba'),
  NicaraguaOriginPlace('7010', 'Granada', 'Diriomo'),
  NicaraguaOriginPlace('7005', 'Granada', 'Diriá'),
  NicaraguaOriginPlace('7515', 'Carazo', 'Dolores'),
  NicaraguaOriginPlace('8510', 'Río San Juan', 'El Almendro'),
  NicaraguaOriginPlace(
    '9323',
    'Región Autónoma de la Costa Caribe Sur',
    'El Ayote',
  ),
  NicaraguaOriginPlace('8525', 'Río San Juan', 'El Castillo'),
  NicaraguaOriginPlace('6545', 'Chontales', 'El Coral'),
  NicaraguaOriginPlace('5532', 'Managua', 'El Crucero'),
  NicaraguaOriginPlace('1010', 'Jinotega', 'El Cuá', aliases: ['El Cúa']),
  NicaraguaOriginPlace('3520', 'León', 'El Jicaral'),
  NicaraguaOriginPlace('0515', 'Nueva Segovia', 'El Jícaro'),
  NicaraguaOriginPlace(
    '9320',
    'Región Autónoma de la Costa Caribe Sur',
    'El Rama',
    aliases: ['Rama'],
  ),
  NicaraguaOriginPlace('7525', 'Carazo', 'El Rosario'),
  NicaraguaOriginPlace('3510', 'León', 'El Sauce'),
  NicaraguaOriginPlace(
    '9316',
    'Región Autónoma de la Costa Caribe Sur',
    'El Tortuguero',
  ),
  NicaraguaOriginPlace('3025', 'Chinandega', 'El Viejo'),
  NicaraguaOriginPlace('4050', 'Matagalpa', 'Esquipulas'),
  NicaraguaOriginPlace('2515', 'Estelí', 'Estelí'),
  NicaraguaOriginPlace('7015', 'Granada', 'Granada'),
  NicaraguaOriginPlace('0505', 'Nueva Segovia', 'Jalapa'),
  NicaraguaOriginPlace('1035', 'Jinotega', 'Jinotega'),
  NicaraguaOriginPlace('7510', 'Carazo', 'Jinotepe'),
  NicaraguaOriginPlace('6510', 'Chontales', 'Juigalpa'),
  NicaraguaOriginPlace(
    '9312',
    'Región Autónoma de la Costa Caribe Sur',
    'Desembocadura de Río Grande',
    city: 'Karawala',
  ),
  NicaraguaOriginPlace(
    '9330',
    'Región Autónoma de la Costa Caribe Sur',
    'Kukrahill',
    aliases: ['Kukra - Hill', 'Kukra Hill'],
  ),
  NicaraguaOriginPlace('6020', 'Masaya', 'La Concepción'),
  NicaraguaOriginPlace('1030', 'Jinotega', 'La Concordia'),
  NicaraguaOriginPlace('7540', 'Carazo', 'La Conquista'),
  NicaraguaOriginPlace(
    '9310',
    'Región Autónoma de la Costa Caribe Sur',
    'La Cruz de Río Grande',
  ),
  NicaraguaOriginPlace(
    '4015',
    'Matagalpa',
    'El Tuma-La Dalia',
    city: 'La Dalia',
    aliases: ['El Tuma - La Dalia', 'Tuma-La Dalia', 'El Tuma'],
  ),
  NicaraguaOriginPlace('6515', 'Chontales', 'La Libertad'),
  NicaraguaOriginPlace('3545', 'León', 'La Paz Centro'),
  NicaraguaOriginPlace('7530', 'Carazo', 'La Paz de Carazo'),
  NicaraguaOriginPlace('2525', 'Estelí', 'La Trinidad'),
  NicaraguaOriginPlace(
    '9315',
    'Región Autónoma de la Costa Caribe Sur',
    'Laguna de Perlas',
  ),
  NicaraguaOriginPlace(
    '1015',
    'Jinotega',
    'Santa María de Pantasma',
    city: 'Las Praderas',
    aliases: ['Sta. María de Pantasma'],
  ),
  NicaraguaOriginPlace('2040', 'Madriz', 'Las Sabanas'),
  NicaraguaOriginPlace('3540', 'León', 'León'),
  NicaraguaOriginPlace('0535', 'Nueva Segovia', 'Macuelizo'),
  NicaraguaOriginPlace('3525', 'León', 'Larreynaga', city: 'Malpaisillo'),
  NicaraguaOriginPlace('5525', 'Managua', 'Managua'),
  NicaraguaOriginPlace('6025', 'Masaya', 'Masatepe'),
  NicaraguaOriginPlace('6010', 'Masaya', 'Masaya'),
  NicaraguaOriginPlace('4030', 'Matagalpa', 'Matagalpa'),
  NicaraguaOriginPlace('5515', 'Managua', 'Mateare'),
  NicaraguaOriginPlace('4040', 'Matagalpa', 'Matiguás'),
  NicaraguaOriginPlace('8505', 'Río San Juan', 'Morrito'),
  NicaraguaOriginPlace('8025', 'Rivas', 'Moyogalpa'),
  NicaraguaOriginPlace('0525', 'Nueva Segovia', 'Mozonte'),
  NicaraguaOriginPlace(
    '9325',
    'Región Autónoma de la Costa Caribe Sur',
    'Muelle de los Bueyes',
  ),
  NicaraguaOriginPlace(
    '9127',
    'Región Autónoma de la Costa Caribe Norte',
    'Mulukukú',
    aliases: ['Mulukuku'],
  ),
  NicaraguaOriginPlace('0510', 'Nueva Segovia', 'Murra'),
  NicaraguaOriginPlace('4045', 'Matagalpa', 'Muy Muy'),
  NicaraguaOriginPlace('3550', 'León', 'Nagarote'),
  NicaraguaOriginPlace('7020', 'Granada', 'Nandaime'),
  NicaraguaOriginPlace('6030', 'Masaya', 'Nandasmo'),
  NicaraguaOriginPlace('6005', 'Masaya', 'Nindirí'),
  NicaraguaOriginPlace('6045', 'Masaya', 'Niquinohomo'),
  NicaraguaOriginPlace(
    '9345',
    'Región Autónoma de la Costa Caribe Sur',
    'Nueva Guinea',
  ),
  NicaraguaOriginPlace('0545', 'Nueva Segovia', 'Ocotal'),
  NicaraguaOriginPlace('2025', 'Madriz', 'Palacagüina'),
  NicaraguaOriginPlace('3065', 'Chinandega', 'Posoltega'),
  NicaraguaOriginPlace('8015', 'Rivas', 'Potosí'),
  NicaraguaOriginPlace(
    '9135',
    'Región Autónoma de la Costa Caribe Norte',
    'Prinzapolka',
  ),
  NicaraguaOriginPlace('2505', 'Estelí', 'Pueblo Nuevo'),
  NicaraguaOriginPlace('3535', 'León', 'Quezalguaque'),
  NicaraguaOriginPlace('0555', 'Nueva Segovia', 'Quilalí'),
  NicaraguaOriginPlace('4005', 'Matagalpa', 'Rancho Grande'),
  NicaraguaOriginPlace('3050', 'Chinandega', 'El Realejo', city: 'Realejo'),
  NicaraguaOriginPlace('8040', 'Rivas', 'Rivas'),
  NicaraguaOriginPlace(
    '9115',
    'Región Autónoma de la Costa Caribe Norte',
    'Rosita',
  ),
  NicaraguaOriginPlace('4010', 'Matagalpa', 'Río Blanco'),
  NicaraguaOriginPlace('8520', 'Río San Juan', 'San Carlos'),
  NicaraguaOriginPlace('4055', 'Matagalpa', 'San Dionisio'),
  NicaraguaOriginPlace('0520', 'Nueva Segovia', 'San Fernando'),
  NicaraguaOriginPlace('3010', 'Chinandega', 'San Francisco del Norte'),
  NicaraguaOriginPlace('5505', 'Managua', 'San Francisco Libre'),
  NicaraguaOriginPlace('4020', 'Matagalpa', 'San Isidro'),
  NicaraguaOriginPlace('8035', 'Rivas', 'San Jorge'),
  NicaraguaOriginPlace(
    '1012',
    'Jinotega',
    'San José de Bocay',
    aliases: ['San José Bocay'],
  ),
  NicaraguaOriginPlace('2045', 'Madriz', 'San José de Cusmapa'),
  NicaraguaOriginPlace('5005', 'Boaco', 'San José de los Remates'),
  NicaraguaOriginPlace('2520', 'Estelí', 'San Juan de Limay'),
  NicaraguaOriginPlace(
    '8530',
    'Río San Juan',
    'San Juan de Nicaragua',
    aliases: ['San Juan del Nicaragua'],
  ),
  NicaraguaOriginPlace('6040', 'Masaya', 'San Juan de Oriente'),
  NicaraguaOriginPlace(
    '2020',
    'Madriz',
    'San Juan del Río Coco',
    aliases: ['San Juan de Río Coco'],
  ),
  NicaraguaOriginPlace('8045', 'Rivas', 'San Juan del Sur'),
  NicaraguaOriginPlace('2035', 'Madriz', 'San Lucas'),
  NicaraguaOriginPlace('7505', 'Carazo', 'San Marcos'),
  NicaraguaOriginPlace('8515', 'Río San Juan', 'San Miguelito'),
  NicaraguaOriginPlace('2530', 'Estelí', 'San Nicolás'),
  NicaraguaOriginPlace('6530', 'Chontales', 'San Pedro de Lóvago'),
  NicaraguaOriginPlace('3005', 'Chinandega', 'San Pedro del Norte'),
  NicaraguaOriginPlace('1020', 'Jinotega', 'San Rafael del Norte'),
  NicaraguaOriginPlace('5535', 'Managua', 'San Rafael del Sur'),
  NicaraguaOriginPlace('4035', 'Matagalpa', 'San Ramón'),
  NicaraguaOriginPlace('1025', 'Jinotega', 'San Sebastián de Yalí'),
  NicaraguaOriginPlace('5020', 'Boaco', 'Santa Lucía'),
  NicaraguaOriginPlace('0540', 'Nueva Segovia', 'Santa María'),
  NicaraguaOriginPlace('3515', 'León', 'Santa Rosa del Peñón'),
  NicaraguaOriginPlace('7535', 'Carazo', 'Santa Teresa'),
  NicaraguaOriginPlace('6520', 'Chontales', 'Santo Domingo'),
  NicaraguaOriginPlace('6525', 'Chontales', 'Santo Tomás'),
  NicaraguaOriginPlace('3020', 'Chinandega', 'Santo Tomás del Norte'),
  NicaraguaOriginPlace('5030', 'Boaco', 'SanÂ Lorenzo'),
  NicaraguaOriginPlace(
    '9130',
    'Región Autónoma de la Costa Caribe Norte',
    'Siuna',
  ),
  NicaraguaOriginPlace('3035', 'Chinandega', 'Somotillo'),
  NicaraguaOriginPlace('2005', 'Madriz', 'Somoto'),
  NicaraguaOriginPlace('4025', 'Matagalpa', 'Sébaco'),
  NicaraguaOriginPlace('3530', 'León', 'Telica'),
  NicaraguaOriginPlace('2015', 'Madriz', 'Telpaneca'),
  NicaraguaOriginPlace('4060', 'Matagalpa', 'Terrabona'),
  NicaraguaOriginPlace('5025', 'Boaco', 'Teustepe'),
  NicaraguaOriginPlace('5530', 'Managua', 'Ticuantepe'),
  NicaraguaOriginPlace('5510', 'Managua', 'Tipitapa'),
  NicaraguaOriginPlace('6015', 'Masaya', 'Tisma'),
  NicaraguaOriginPlace('8005', 'Rivas', 'Tola'),
  NicaraguaOriginPlace('3030', 'Chinandega', 'Puerto Morazán', city: 'Tonalá'),
  NicaraguaOriginPlace('2010', 'Madriz', 'Totogalpa'),
  NicaraguaOriginPlace(
    '5520',
    'Managua',
    'Villa El Carmen',
    aliases: ['Villa Carlos Fonseca'],
  ),
  NicaraguaOriginPlace('6540', 'Chontales', 'Villa Sandino'),
  NicaraguaOriginPlace('3040', 'Chinandega', 'Villanueva'),
  NicaraguaOriginPlace(
    '9125',
    'Región Autónoma de la Costa Caribe Norte',
    'Waslala',
  ),
  NicaraguaOriginPlace(
    '9105',
    'Región Autónoma de la Costa Caribe Norte',
    'Waspán',
    aliases: ['Waspam'],
  ),
  NicaraguaOriginPlace(
    '0560',
    'Nueva Segovia',
    'Wiwilí de Nueva Segovia',
    city: 'Wiwilí',
    aliases: ['Wiwili de Nueva Segovia', 'Wiwilí'],
  ),
  NicaraguaOriginPlace(
    '1005',
    'Jinotega',
    'Wiwilí de Jinotega',
    aliases: ['Wiwilí'],
  ),
  NicaraguaOriginPlace('2030', 'Madriz', 'Yalagüina'),
];
